resilience4j:
  circuitbreaker:
    instances:
      default:
        register-health-indicator: false
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 6
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        automatic-transition-from-open-to-half-open-enabled: true
        recordFailurePredicate:
          - io.github.robwin.exception.RecordFailurePredicate
          - java.util.concurrent.TimeoutException
