resilience4j:
  circuit breaker:
    instances:
      default:
        register-health-indicator: false
        sliding-window-size: 2
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 4
        wait-duration-in-open-state: 20s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        ignore-exceptions:
          - feign.FeignException.Forbidden
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - com.store.cbapp.exception.ServiceUnavailableException
          - feign.FeignException.ServiceUnavailable
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException